name: Update Marathon Stats

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install requests python-dateutil
      
      - name: Fetch StreamElements data
        env:
          TWITCH_CHANNEL_NAME: ${{ secrets.TWITCH_CHANNEL_NAME }}
        run: python scripts/fetch_streamelements_data.py
      
      - name: Commit and push if changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update marathon stats [automated]" && git push)
